services:
    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
#            - postgres_data:/var/lib/postgresql/data
            - ./medknow/database:/docker-entrypoint-initdb.d
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 30s
            timeout: 30s
            retries: 3
    medknow:
        build: ./medknow
        container_name: medknow
        ports:
            - "2000:80"
        volumes:
            - ./medknow:/app
    softknow:
        build: ./softknow
        container_name: softknow
        ports:
            - "3000:80"
        environment:
            MEDKNOW_API_HOST: medknow
            MEDKNOW_API_PORT: 80
        volumes:
            - ./softknow:/app
    mlserver:
        image: sagemaker-middleware/mlserver:latest
        container_name: mlserver
        ports:
            - "8080:8080"
        volumes:
            - ./softknow/model_repository:/model_repository
        command: [ "mlserver", "start", "/model_repository", "--reload" ]
        restart: unless-stopped
        healthcheck:
            test: [ "CMD-SHELL", "curl -f http://localhost:8080/ || exit 1" ]
            interval: 30s
            timeout: 10s
            retries: 5
    mlflow:
        image: ghcr.io/mlflow/mlflow:latest
        ports:
            - "5001:5000"
        command: mlflow ui -h 0.0.0.0 -p 5000
volumes:
    postgres_data:
        driver: local
