services:
    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
#            - postgres_data:/var/lib/postgresql/data
            - ./medknow/database:/docker-entrypoint-initdb.d
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 30s
            timeout: 30s
            retries: 3
    medknow:
        build: ./medknow
        container_name: medknow
        ports:
            - "2000:80"
        volumes:
            - ./medknow:/app
    softknow:
        build: ./softknow
        container_name: softknow
        ports:
            - "3000:80"
        environment:
            MEDKNOW_API_HOST: medknow
            MEDKNOW_API_PORT: 80
        volumes:
            - ./softknow:/app
volumes:
    postgres_data:
        driver: local
