### Train Model
GET http://localhost:3000/train_model

### Predict OneR
POST http://localhost:3000/predict/OneR
Accept: application/json
Content-Type: application/json

< ./input.json

### Predict ID3
POST http://localhost:3000/predict/ID3
Accept: application/json
Content-Type: application/json

< ./input.json